/** Nombre de icono SVG por módulo del menú lateral */
export const ICONO_MODULO = {
  Inicio: 'home',
  Incidencias: 'alert',
  Ventas: 'cart',
  'Escáner caja': 'scan',
  'Corte de caja': 'register',
  Recolecciones: 'dollar',
  'Liquidación recolecciones': 'register',
  Productos: 'package',
  'Venta en Ruta': 'truck',
  Compras: 'truck',
  Checador: 'scan',
  'Check List': 'file',
  Proveedores: 'building',
  Clientes: 'users',
  Usuarios: 'userCog',
  Consultas: 'search',
  Estadisticas: 'chart',
  'Resumen operativo': 'chart',
  Reportes: 'file',
  Contabilidad: 'dollar',
  'Nómina': 'dollar',
  'Panel RT': 'truck',
  'IE VIRTUAL': 'chart',
  'IE ABARROTES': 'package',
  'Auto Fin': 'dollar',
  Crédito: 'file',
  Cobranza: 'dollar',
  'Vales y Préstamos': 'file',
  'Corte Virtual': 'register',
  'Corte Abarrotes': 'package',
  'Corte Garage': 'building',
  Configuracion: 'settings',
  Ayuda: 'help',
};

/** Color de acento por módulo (iconos del menú y cabecera). */
export const COLOR_MODULO = {
  Inicio: '#3b66b5',
  Incidencias: '#dc2626',
  Ventas: '#e19929',
  'Escáner caja': '#0ea5e9',
  'Corte de caja': '#2e7d32',
  Recolecciones: '#0d9488',
  'Liquidación recolecciones': '#047857',
  Productos: '#8b5cf6',
  'Venta en Ruta': '#0f766e',
  Compras: '#0d9488',
  Checador: '#c47f15',
  'Check List': '#0f766e',
  Proveedores: '#6366f1',
  Clientes: '#ec4899',
  Usuarios: '#3b66b5',
  Consultas: '#0891b2',
  Estadisticas: '#16a34a',
  'Resumen operativo': '#0d9488',
  Reportes: '#64748b',
  Contabilidad: '#7c3aed',
  'Nómina': '#0d9488',
  'Panel RT': '#047857',
  'IE VIRTUAL': '#8e44ad',
  'IE ABARROTES': '#b5a642',
  'Auto Fin': '#0f766e',
  Crédito: '#b45309',
  Cobranza: '#0f766e',
  'Vales y Préstamos': '#b45309',
  'Corte Virtual': '#8e44ad',
  'Corte Abarrotes': '#b5a642',
  'Corte Garage': '#7f8c8d',
  Configuracion: '#5c5c5c',
  Ayuda: '#b5b03e',
};

export function iconoDeModulo(moduloId) {
  return ICONO_MODULO[moduloId] || 'circle';
}

export function colorDeModulo(moduloId) {
  return COLOR_MODULO[moduloId] || 'var(--brand-blue)';
}
