/** Contenido del módulo Tutorial (POS). Imágenes en /public/tutorial-negativos/ */

export const TUTORIALES = [
  {
    id: 'negativos-pagare',
    titulo: 'Negativos, Pagaré, Abonos y Liquidaciones',
    resumen:
      'Cómo manejar la alerta DINERO EN RECUPERACIÓN: abono, liquidar, pagaré solo en recolección, y qué no puede hacer el cubre turno.',
    secciones: [
      {
        id: 'flujo',
        titulo: '1. El mapa completo',
        cuerpo: [
          'Cuando la caja o una deuda queda en rojo, el flujo correcto es:',
          '1. Aparece la alerta **DINERO EN RECUPERACIÓN** (**Negativo**).',
          '2. Si aún falta dinero → **Abono** (pago parcial) — lo hace el **cajero**.',
          '3. Cuando ya se recuperó todo (**Negativo = $0**) → **Liquidar** — lo hace el **cajero**.',
          '4. **Pagaré** (al final): **únicamente** si el negativo **sigue presente durante una recolección**. Documenta la deuda (2 tickets); no la cierra.',
        ],
        imagen: '/tutorial-negativos/tutorial-01-flujo-negativos.png',
        imagenAlt: 'Flujo Negativo → Abono → Liquidar → Pagaré',
        notas: [
          '**Después de una recolección:** el **cajero** es el **responsable de la recuperación** (abonar / liquidar lo pendiente).',
          'Esto es el *negativo de dinero* (caja / deuda). El inventario negativo en Productos es otro tema (solo Admin).',
        ],
      },
      {
        id: 'negativo',
        titulo: '2. Qué es el “Negativo”',
        cuerpo: [
          'En el corte verás una alerta parpadeante cuando hay un **pagaré** o **préstamo de área** abierto, o la **caja chica** está en negativo.',
          '**Negativo** = lo que aún falta recuperar. **Recuperado** = lo que ya cubrió la venta del corte.',
          'La venta del corte (efectivo) va reduciendo el negativo sola: cada venta suma a Recuperado y baja Negativo.',
        ],
        imagen: '/tutorial-negativos/tutorial-02-alerta-dinero-recuperacion.png',
        imagenAlt: 'Alerta DINERO EN RECUPERACIÓN',
      },
      {
        id: 'roles',
        titulo: '3. Quién hace qué',
        cuerpo: [
          '**Cajero:** Abono y Liquidar.',
          '**Admin / Gerente:** Abono, Liquidar y Pagaré (en recolección).',
          '**Recolector:** Pagaré en recolección (no abona/liquida en el corte).',
          '**Cubre turno (CT):** solo **ve** la alerta. **No** puede Abonar, Liquidar ni Pagaré.',
        ],
        imagen: '/tutorial-negativos/tutorial-04-roles-quien-hace-que.png',
        imagenAlt: 'Tabla de roles',
      },
      {
        id: 'cubre-turno',
        titulo: '4. Cubre turno: no abona ni liquida',
        cuerpo: [
          'El **cubre turno** puede ver la alerta, pero **no** puede pulsar **Abono** ni **Liquidar**.',
          'Eso lo hace el **cajero** cuando **recibe el turno del CT** (entra con su sesión de cajero).',
          'Mensaje típico para CT: *NEGATIVO RECUPERADO — EL CAJERO DEBE LIQUIDAR O ABONAR EN SU SESIÓN*.',
        ],
        imagen: '/tutorial-negativos/tutorial-07-cubre-turno-cajero.png',
        imagenAlt: 'Cubre turno vs cajero',
        notas: [
          '**Después de una recolección, el cajero es el responsable de la recuperación.**',
        ],
      },
      {
        id: 'abono',
        titulo: '5. Abono (pago parcial)',
        cuerpo: [
          'Usa **Abono** cuando todavía hay **Negativo > $0**.',
          '1. Entra como **cajero** (si venía un CT, el cajero retoma el turno).',
          '2. En la alerta pulsa **Abono** y captura el monto.',
          '3. El saldo baja. Si llega a $0, se liquida solo.',
          'También puedes abonar en **Vales y Préstamos → Pagaré** (y otros documentos).',
        ],
        imagen: '/tutorial-negativos/tutorial-05-abono-vs-liquidar.png',
        imagenAlt: 'Abono vs Liquidar',
      },
      {
        id: 'liquidar',
        titulo: '6. Liquidar (cerrar la deuda)',
        cuerpo: [
          'Usa **Liquidar** cuando el **Negativo ya está en $0** pero la alerta sigue visible.',
          'Verás: **NEGATIVO RECUPERADO, FAVOR DE LIQUIDAR Y PAGAR PRÉSTAMO**.',
          'El **cajero** (nunca el CT) pulsa **Liquidar**. La alerta desaparece; no se imprime ticket nuevo.',
        ],
        imagen: '/tutorial-negativos/tutorial-03-negativo-recuperado-liquidar.png',
        imagenAlt: 'Negativo recuperado — Liquidar',
      },
      {
        id: 'pagare',
        titulo: '7. Pagaré (solo en recolección, al final)',
        cuerpo: [
          '**Regla de oro:** el Pagaré se genera **únicamente** cuando el negativo está presente **durante una recolección**.',
          'Va **al final** del flujo: primero recupera (venta / abono / liquidar); si al recolectar **aún** hay negativo, entonces se documenta.',
          'Lo genera **Admin / Gerente / Recolector**. Imprime **2 tickets**.',
          'Generar el pagaré **no liquida** la deuda: solo la documenta.',
          'Después, el **cajero** hace el seguimiento en **Vales y Préstamos → Pagaré** (Abonar / Liquidar).',
        ],
        imagen: '/tutorial-negativos/tutorial-06-pagare-ticket.png',
        imagenAlt: 'Ticket Pagaré ×2',
        notas: [
          '**Después de la recolección, el cajero es el responsable de la recuperación.**',
        ],
      },
      {
        id: 'orden',
        titulo: '8. Orden correcto en tienda',
        cuerpo: [
          '1. Capturar **todos** los gastos del turno (incl. bonos pagados de caja).',
          '2. Atender **DINERO EN RECUPERACIÓN**: Abono / Liquidar (**cajero**).',
          '3. **Cerrar corte**.',
          '4. **Recolectar** — si el negativo sigue presente → **Pagaré**.',
          '5. Después de la recolección → el **cajero** es responsable de la recuperación.',
        ],
      },
      {
        id: 'frase',
        titulo: 'Frase para capacitar',
        cuerpo: [
          'Primero recupera: **Abono** o **Liquidar** (siempre el **cajero**, nunca el cubre turno).',
          'El **Pagaré** va **al final** y **solo** si el negativo está presente **durante la recolección**.',
          'Después de recolectar, el **cajero** es el **responsable de la recuperación**.',
        ],
      },
    ],
  },
  {
    id: 'cobros-caja',
    titulo: 'Cobros en caja: efectivo, dólares, tarjeta y recargas',
    resumen:
      'Cómo armar el ticket, cobrar en pesos o dólares, cobrar con tarjeta, y registrar recargas de celular (como gasto del corte, no en Ventas).',
    secciones: [
      {
        id: 'mapa-cobros',
        titulo: '1. Mapa de cobros',
        cuerpo: [
          'Ruta: menú → **Ventas**.',
          '**Efectivo MXN / USD** y **Tarjeta** se cobran en el modal **Cobrar venta**.',
          'Las **recargas de celular** **no** se cobran en Ventas: se registran en **Corte Virtual** o **Corte Abarrotes** → **Gastos del turno**.',
        ],
        imagen: '/tutorial-cobros/cobro-00-mapa.png',
        imagenAlt: 'Mapa: Ticket, Efectivo MXN, USD, Tarjeta, Recargas',
      },
      {
        id: 'ticket',
        titulo: '2. Armar el ticket y cobrar',
        cuerpo: [
          '1. Entra a **Ventas** y revisa la tienda en el encabezado.',
          '2. Agrega productos: escanea en **Código o nombre…**, toca Favoritos/catálogo, o usa la cámara.',
          '3. En **Ticket** ajusta cantidades o usa **Quitar**.',
          '4. Revisa el **TOTAL $… MXN**.',
          '5. Pulsa el botón verde **Cobrar** (solo si hay productos).',
          '6. Se abre el modal **Cobrar venta**.',
        ],
        imagen: '/tutorial-cobros/cobro-01-ticket-cobrar.png',
        imagenAlt: 'Pantalla Ventas: ticket y botón Cobrar',
        notas: [
          'Si el carrito está vacío, **Cobrar** está deshabilitado.',
          'Arriba se muestra el **Dólar: $X.XX** (tipo de cambio activo).',
        ],
      },
      {
        id: 'efectivo-mxn',
        titulo: '3. Efectivo en pesos (MXN)',
        cuerpo: [
          '1. En **Forma de pago** elige **Efectivo**.',
          '2. En moneda elige **Pesos (MXN)**.',
          '3. Opciones:',
          '   · **Monto exacto · $… MXN** → cambio $0.00',
          '   · **O pagar con billete…** → $20 / $50 / $100 / $200 / $500 / $1000 MXN',
          '4. Revisa **Cambio: $… MXN**.',
          '5. Pulsa **Finalizar venta**.',
          '6. En **Venta registrada** revisa el cambio y pulsa **Cerrar** (o **Imprimir ticket**).',
        ],
        imagen: '/tutorial-cobros/cobro-02-efectivo-pesos.png',
        imagenAlt: 'Modal Cobrar venta — Efectivo MXN',
        notas: [
          'No hay campo libre de monto: solo **Monto exacto** o un billete de la lista.',
          'Si falta dinero: *Monto insuficiente*. Si no elegiste nada: *Selecciona la denominación o Monto exacto.*',
        ],
      },
      {
        id: 'efectivo-usd',
        titulo: '4. Efectivo en dólares (USD)',
        cuerpo: [
          '1. **Forma de pago** → **Efectivo**.',
          '2. Moneda → **Dólares (USD)**.',
          '3. El total del ticket sigue en **MXN**. El sistema convierte con el tipo de cambio del encabezado.',
          '4. Elige **Monto exacto · $… MXN** o un billete USD ($1 / $5 / $10 / $20 / $50 / $100).',
          '5. El **Cambio siempre se muestra en pesos (MXN)**.',
          '6. **Finalizar venta**.',
        ],
        imagen: '/tutorial-cobros/cobro-03-efectivo-dolares.png',
        imagenAlt: 'Modal Cobrar venta — Efectivo USD',
        notas: [
          'El tipo de cambio se configura en **Configuración → Tipo de cambio (1 USD → MXN)**.',
          'Se guarda como **Efectivo USD**.',
        ],
      },
      {
        id: 'tarjeta',
        titulo: '5. Pago con tarjeta',
        cuerpo: [
          '1. En **Forma de pago** elige **Tarjeta**.',
          '2. Verás: **Cobro exacto · Tarjeta · $… MXN** (sin cambio).',
          '3. Opcional: llena **Referencia / folio (opcional)** (últimos dígitos, autorización…).',
          '4. **Cobra primero en la terminal física** de la tienda.',
          '5. Regresa al POS y pulsa **Finalizar venta**.',
          '6. Cierra el modal **Venta registrada**.',
        ],
        imagen: '/tutorial-cobros/cobro-04-tarjeta.png',
        imagenAlt: 'Modal Cobrar venta — Tarjeta',
        notas: [
          'El POS **no cobra** en la terminal: solo registra. Si finalizas sin cobrar en la máquina, el corte no cuadrará.',
          '**Transferencia** y **QR** funcionan igual (cobro exacto + referencia opcional), si están activos en Configuración.',
        ],
      },
      {
        id: 'venta-ok',
        titulo: '6. Venta registrada',
        cuerpo: [
          'Tras **Finalizar venta** aparece **Venta registrada** con el cobro y el cambio (si aplica).',
          'Pulsa **Cerrar** para seguir vendiendo. Puedes **Imprimir ticket** si hay impresora.',
          'Si necesitas el ticket otra vez: **Reimprimir último ticket**.',
        ],
        imagen: '/tutorial-cobros/cobro-06-venta-registrada.png',
        imagenAlt: 'Modal Venta registrada',
      },
      {
        id: 'recargas',
        titulo: '7. Recargas de celular (gasto del corte)',
        cuerpo: [
          '**Importante:** las recargas **NO** se cobran en **Ventas**. No bajan inventario ni van como venta.',
          'Se registran como **gasto del turno** (egreso de efectivo / nómina del empleado).',
          '1. Menú → **Corte Virtual** o **Corte Abarrotes**.',
          '2. En **Gastos del turno**:',
          '   · **Categoría** → **EMPLEADO**',
          '   · **Empleado** → elige a la persona',
          '   · **Concepto** → **Recargas** (plantilla *Recargas*)',
          '   · **Monto** → escribe el importe',
          '3. Pulsa **Agregar**.',
        ],
        imagen: '/tutorial-cobros/cobro-05-recargas-gasto.png',
        imagenAlt: 'Gastos del turno — EMPLEADO / Recargas',
        notas: [
          'Las recargas **descuentan al empleado** en nómina.',
          'Deben capturarse **antes** de recolectar, para que la caja chica cuadre.',
        ],
      },
      {
        id: 'errores-cobro',
        titulo: '8. Errores frecuentes',
        cuerpo: [
          '· Vender en **tienda equivocada**.',
          '· En efectivo: no elegir billete ni **Monto exacto**.',
          '· **Tarjeta:** finalizar en el POS sin cobrar en la terminal.',
          '· Intentar \"vender\" una **recarga** en Ventas (debe ir a **Gastos del turno**).',
          '· No revisar el **Cambio** en efectivo MXN/USD.',
        ],
      },
      {
        id: 'frase-cobro',
        titulo: 'Frase para capacitar',
        cuerpo: [
          'En **Ventas**: arma el ticket → **Cobrar** → elige **Efectivo** (pesos o dólares) o **Tarjeta** → **Finalizar venta**.',
          'Las **recargas** van en el **corte** como gasto **EMPLEADO → Recargas**, nunca como venta.',
        ],
      },
    ],
  },
  {
    id: 'compras',
    titulo: 'Ingresar compras al sistema',
    resumen:
      'Cómo pedir mercancía a un proveedor, recibirla (escaneo) y subirla al inventario — o registrar una entrega directa.',
    secciones: [
      {
        id: 'mapa-compras',
        titulo: '1. Mapa del flujo',
        cuerpo: [
          'Ruta: menú → **Compras** → pestaña **Herramienta de compra**.',
          'Flujo normal (mayorista): **Proveedor** → **Pedido** (no mueve inventario) → **Recepción** (sí mueve inventario).',
          'Atajo: **Entrega directa a inventario** (entra al stock de inmediato).',
        ],
        imagen: '/tutorial-compras/compra-00-mapa.png',
        imagenAlt: 'Flujo Proveedor → Pedido → Recepción → Inventario',
      },
      {
        id: 'elegir-proveedor',
        titulo: '2. Elegir proveedor',
        cuerpo: [
          '1. Abre **Compras** → **Herramienta de compra**.',
          '2. En **Proveedor** elige al proveedor (ej. Sabritas).',
          '3. En **Pedido pendiente (recepción)** deja **— Nuevo pedido —** si vas a crear uno nuevo.',
          '4. Elige el camino:',
          '   · **Pedido (recepción después)** — genera pedido y recibes después',
          '   · **Entrega directa a inventario** — ya te entregaron y quieres subir stock ya',
          '5. Si falta el proveedor: **Gestionar proveedores** (alta solo Admin).',
        ],
        imagen: '/tutorial-compras/compra-01-proveedor.png',
        imagenAlt: 'Selector de proveedor y botones de pedido / entrega directa',
        notas: [
          'Sin proveedor: *Selecciona primero un proveedor.*',
          'El proveedor debe tener productos en su **catálogo** (módulo Proveedores).',
        ],
      },
      {
        id: 'nuevo-pedido',
        titulo: '3. Generar un pedido (sin tocar inventario)',
        cuerpo: [
          '1. Pulsa **Pedido (recepción después)**.',
          '2. Se abre **Nuevo pedido · {proveedor}**.',
          '3. Revisa la tabla: **Sugerido** propone cantidades (stock + ventas).',
          '4. En la columna **Pedido** captura lo que vas a pedir (Enter acepta la sugerida).',
          '5. Opcional: **Notas al proveedor**.',
          '6. Pulsa **Generar pedido (sin tocar inventario)**.',
          '7. Puedes **Imprimir pedido** para el proveedor.',
        ],
        imagen: '/tutorial-compras/compra-02-nuevo-pedido.png',
        imagenAlt: 'Panel Nuevo pedido con columna Pedido y Sugerido',
        notas: [
          '**Importante:** generar el pedido **NO** mueve el inventario. El stock sube al **recibir**.',
          'Si no capturas cantidades: *Captura cantidades en la columna Pedido…*',
        ],
      },
      {
        id: 'recepcion',
        titulo: '4. Recibir mercancía (sí sube inventario)',
        cuerpo: [
          '1. Con el mismo proveedor, en **Pedido pendiente (recepción)** elige el pedido, **o**',
          '   ve a **Historial** → fila en estado **pedido** → **Recibir**.',
          '2. Se abre **Recepción de mercancía · {proveedor}**.',
          '3. Escanea en *Escanear código para sumar +1 en recepción…* o captura la columna **Recepción**.',
          '4. Pulsa **Recibir mercancía**.',
          '5. Confirma el prompt: *¿Cuál es el total del ticket del proveedor?*',
          '6. El sistema sube el stock y marca la compra como **recibida**.',
        ],
        imagen: '/tutorial-compras/compra-03-recepcion.png',
        imagenAlt: 'Recepción de mercancía con escaneo y Recibir mercancía',
        notas: [
          'Solo productos de la lista del pedido. Si escaneas otro: *Producto no está en la lista*.',
          'En tienda el stock entra a **piso**; en sucursal **CEDIS** entra al almacén CEDIS.',
        ],
      },
      {
        id: 'entrega-directa',
        titulo: '5. Entrega directa (atajo)',
        cuerpo: [
          'Úsala cuando el proveedor ya te entregó y no necesitas pedido previo.',
          '1. Elige proveedor → **Entrega directa a inventario**.',
          '2. Escanea o captura **Cantidad entregada**.',
          '3. Opcional: **Notas de la entrega**.',
          '4. Pulsa **Registrar entrega e inventario**.',
          '5. El stock entra **de inmediato**.',
        ],
        imagen: '/tutorial-compras/compra-04-entrega-directa.png',
        imagenAlt: 'Entrega directa a inventario',
      },
      {
        id: 'historial',
        titulo: '6. Historial',
        cuerpo: [
          'Pestaña **Historial de compras**: ves pedidos pendientes y recepciones.',
          'Estado **pedido** (naranja) → botón **Recibir**.',
          'Estado **recibida** (verde) → **Imprimir recepción** / **Imprimir pedido**.',
        ],
        imagen: '/tutorial-compras/compra-05-historial.png',
        imagenAlt: 'Historial de compras con estados pedido y recibida',
      },
      {
        id: 'errores-compras',
        titulo: '7. Errores frecuentes',
        cuerpo: [
          '· No elegir proveedor.',
          '· Generar pedido sin cantidades en **Pedido**.',
          '· Creer que el pedido ya subió inventario (solo la **recepción** lo hace).',
          '· Escaneo de producto que no está en el pedido/catálogo del proveedor.',
          '· Proveedor sin catálogo vinculado (hay que armarlo en **Proveedores**).',
        ],
      },
      {
        id: 'frase-compras',
        titulo: 'Frase para capacitar',
        cuerpo: [
          '**Pedido** = ordenar (sin stock). **Recibir mercancía** = ya llegó y **sí** sube inventario.',
          'Si ya te entregaron sin pedido: **Entrega directa a inventario**.',
        ],
      },
    ],
  },
];
